import { factories } from '@strapi/strapi';

/**
 * Daily rollups are read by the admin Analytics dashboard via the
 * /content-manager admin routes, not the content API. Block content-API
 * verbs here as defence in depth.
 */
export default factories.createCoreController(
  'api::analytics-daily-rollup.analytics-daily-rollup',
  () => ({
    async find(ctx) {
      return ctx.forbidden('Analytics data is admin-only.');
    },
    async findOne(ctx) {
      return ctx.forbidden('Analytics data is admin-only.');
    },
    async create(ctx) {
      return ctx.forbidden('Rollups are generated by the nightly cron.');
    },
    async update(ctx) {
      return ctx.forbidden('Analytics data is admin-only.');
    },
    async delete(ctx) {
      return ctx.forbidden('Analytics data is admin-only.');
    },
  })
);
