/**
 * Idempotent: ensure a read-only API token named "nextjs-public"
 * exists in the Strapi admin, then dump its plaintext value to
 *   .runtime/public-api-token.txt
 *
 * Strapi only ever returns the plaintext of an API token at the
 * moment of creation (it stores a salted hash afterwards), so we
 * have to capture it on first boot. Subsequent boots find the
 * existing token row and skip; the file is created exactly once.
 *
 * The Next.js app reads this file (or its env equivalent
 * `STRAPI_PUBLIC_TOKEN`) and uses it for every read.
 */
import type { Core } from '@strapi/strapi';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';

const TOKEN_NAME = 'nextjs-public';
const TOKEN_FILE_REL = '.runtime/public-api-token.txt';

export async function ensurePublicApiToken(strapi: Core.Strapi) {
  const tokenService = strapi.service('admin::api-token');

  const existing = await tokenService.getByName(TOKEN_NAME);
  if (existing) {
    strapi.log.info(
      `[ensure-api-token] "${TOKEN_NAME}" already exists (id=${existing.id}). Skipping.`
    );
    return;
  }

  const created = await tokenService.create({
    name: TOKEN_NAME,
    description:
      'Read-only token used by the INSPIRE AFRICA Next.js app for public content fetching. Auto-generated by bootstrap; rotate via the admin UI as needed.',
    type: 'read-only',
    lifespan: null, // never expires
  });

  // Strapi hashes the token before storage. The plaintext is only
  // present on the `accessKey` field of the create() return value.
  const plaintext = created.accessKey;
  if (!plaintext) {
    strapi.log.error(
      '[ensure-api-token] Token created but accessKey was not returned — cannot persist plaintext.'
    );
    return;
  }

  const runtimeDir = resolve(process.cwd(), '.runtime');
  if (!existsSync(runtimeDir)) mkdirSync(runtimeDir, { recursive: true });
  const tokenFile = resolve(process.cwd(), TOKEN_FILE_REL);
  writeFileSync(tokenFile, plaintext, { mode: 0o600 });

  strapi.log.info(
    `[ensure-api-token] Created token "${TOKEN_NAME}" — plaintext saved to ${TOKEN_FILE_REL}`
  );
  strapi.log.info(
    `[ensure-api-token] Next.js app should set STRAPI_PUBLIC_TOKEN to this value (already written to file for first-boot convenience).`
  );
}
